// ============================================================
// Emerging Technologies Data — sourced from the official lesson
// ============================================================
import { EmergingTechnology } from '@/lib/types';

export const emergingTechnologies: EmergingTechnology[] = [
  {
    id: 'autonomous-driving',
    nameEn: 'Autonomous Driving',
    nameAr: 'القيادة الذاتية',
    definition: 'A technology that uses AI to drive a vehicle without human operation.',
    explanation: 'It uses cameras and sensors to recognize the surroundings, makes driving decisions, and controls a vehicle. Because a delay of even 0.1 seconds can lead to an accident, edge computing, in which processing is performed instantly on the vehicle itself rather than sending data to the cloud for judgment, is used.',
    realWorldExample: 'Tesla Autopilot, Waymo self-driving taxis, autonomous delivery vehicles',
    youtubeVideoId: 'aaOB-ErYq6Y',
    teacherQuestion: 'In autonomous driving, why is it necessary to process data instantly on the vehicle side using edge computing, rather than sending the data to the cloud for judgment?',
    image: {
      src: '/assets/lesson1/modern-tech/autonomous-car.webp',
      alt: 'Autonomous self-driving vehicle with sensors',
      caption: 'A self-driving car decides on board (edge computing), without waiting for the cloud.',
      source: 'Wikimedia Commons'
    }
  },
  {
    id: 'edge-computing',
    nameEn: 'Edge Computing',
    nameAr: 'الحوسبة الطرفية',
    definition: 'Processing data on the device itself, instantly, instead of sending it to the cloud.',
    explanation: 'Edge computing moves processing closer to where data is generated. In autonomous driving, for example, the car processes sensor data on board because sending it to the cloud and waiting for a response would be too slow — a delay of even 0.1 seconds can cause an accident.',
    realWorldExample: 'Self-driving cars, smart factory sensors, augmented reality glasses',
    youtubeVideoId: 'cEOUeItHDdo',
    teacherQuestion: 'Can you think of other situations where processing data instantly on the device (edge computing) is better than sending it to the cloud?',
    keyTerm: 'edge computing — processing data on the device itself, instantly, instead of sending it to the cloud.'
  },
  {
    id: 'ar',
    nameEn: 'AR (Augmented Reality)',
    nameAr: 'الواقع المعزز',
    definition: 'A technology that overlays digital information on real-world images.',
    explanation: 'AR adds digital layers — text, images, 3D objects — on top of what you see in the real world, typically through a phone camera or smart glasses. The real environment is still visible, but enhanced with digital information.',
    realWorldExample: 'Pokémon GO, Instagram/Snapchat filters, IKEA Place app (furniture preview), museum guides',
    youtubeVideoId: 'WxzcD04rwc8',
    teacherQuestion: 'What is the difference between AR and VR? Which one keeps you connected to the real world?',
    image: {
      src: '/assets/lesson1/modern-tech/ar-example.svg',
      alt: 'Augmented Reality on a mobile device',
      caption: 'AR adds digital layers to the real world.',
      source: 'Wikimedia Commons'
    }
  },
  {
    id: 'vr',
    nameEn: 'VR (Virtual Reality)',
    nameAr: 'الواقع الافتراضي',
    definition: 'A technology that allows users to immerse themselves in a virtual space generated by a computer.',
    explanation: 'VR completely replaces your visual environment with a computer-generated world. Using a headset, you can look around, interact with virtual objects, and feel as though you are inside the digital environment.',
    realWorldExample: 'Meta Quest, PlayStation VR, virtual tours of museums and historical sites, surgical training simulations',
    youtubeVideoId: 'd_k8S779Z-M',
    teacherQuestion: 'How could VR be used in education? Think of a subject where "being inside" the content would help students learn.',
    image: {
      src: '/assets/lesson1/modern-tech/vr-headset.svg',
      alt: 'VR headset in use',
      caption: 'VR replaces the real world with a virtual one.',
      source: 'Wikimedia Commons'
    }
  },
  {
    id: 'quantum-computing',
    nameEn: 'Quantum Computing',
    nameAr: 'الحوسبة الكمية',
    definition: 'A technology expected to dramatically speed up computations that are difficult or impossible for traditional computers, by using the principles of quantum mechanics.',
    explanation: 'Classical computers use bits (0 or 1). Quantum computers use qubits, which can be in a state of superposition — a combination of 0 and 1 at once. This lets many qubits represent a much larger space of states simultaneously, enabling massive parallel processing for certain problems.',
    realWorldExample: 'IBM Quantum, Google Sycamore — used for drug discovery research, cryptography, optimization problems',
    youtubeVideoId: 'JhHMJCUmq28',
    teacherQuestion: 'A classical bit can be 0 OR 1. A qubit can be both at once (superposition). Why does this make quantum computers potentially much faster for certain problems?',
    image: {
      src: '/assets/lesson1/modern-tech/quantum-computer.svg',
      alt: 'IBM Quantum Computer',
      caption: 'A classical bit holds one state; a qubit uses superposition.',
      source: 'IBM Research'
    }
  }
];
